version: '3'
services:
  db:
    container_name: pg-container
    image: postgres:11.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=95751535r
      - POSTGRES_DATABASE=escalas_ji
    volumes:
      - ./data:/data/db
    ports:
      - '5432:5432'
  api:
    container_name: api-escalas-ji
    build: .
    image: escalas_ji
    restart: always
    command: bash -c "npx prisma generate && npm start"
    environment:
      - DATABASE_URL=postgresql://postgres:95751535r@db:5432/escalas_ji
    volumes:
      - ./dist/:/usr/src/escalas_ji/dist/
      - ./package.json:/usr/src/escalas_ji/package.json
      - ./prisma:/usr/src/escalas_ji/prisma
    ports:
      - "5050:5050"
    depends_on:
      - db
